### ISSUE TITLE
dump to /vol/cndumper/

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-cndumper#1]

**Comment by iainbryson** [comment]
Can you explain in more detail what you want with this and how it related to dtu-compute/dtu-enote#21 ?

**Comment by dtu-compute** [comment]
In dtu-compute/dtu-enote#21 I write the volume as `/vol/cndumper/01005-users.yaml:/users.yaml` where this ticket is a subset of that process. I.e. just moving the 0xxxx-users|groups.yaml files to `/vol/cndumper` where right now they are mixed with the config files.

In a way you can close this ticket.

**Comment by iainbryson** [comment]
OK.  Let's track all the work in dtu-compute/dtu-enote#21
